- name: "Installing boto3"
  pip:
      name: boto3
- name: "Creating a Security Group"
  ec2_group:
      name: "{{ security_group }}"
      description: "Security Group that allow all trafic"
      region: "{{region}}"
      rules:
          - proto: tcp
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0
      rules_egress:
          - proto: tcp
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0
- name: "Launching the Master over AWS  ec2 instance"
  ec2:
      key_name: "{{ key_name  }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image_id }}"
      count: "{{ master_count }}"
      assign_public_ip: yes
      region: "{{region}}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      instance_tags: "{{ tag_master }}"
      group: "{{security_group}}"

- name: "Launching the Worker Node over AWS  ec2 instance"
  ec2:
      key_name: "{{ key_name  }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image_id }}"
      count: "{{ worker_count }}"
      assign_public_ip: yes
      region: ap-south-1
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      instance_tags: "{{ tag_worker }}"
      group: "{{security_group}}"

